---
abstract: 'easy manipulation of JSON headers'
author:
  - 'Michael Peters <mpeters@plusthree.com>'
build_requires:
  JSON: 2.02
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-Application-Plugin-JSON
provides:
  CGI::Application::Plugin::JSON:
    file: lib/CGI/Application/Plugin/JSON.pm
    version: 1.01
requires:
  CGI::Application: 4
  JSON::Any: 1.14
  Test::More: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.01
